---
title: "Solutions exercices chapitre 3"
header-includes:
- \usepackage{amsmath,amssymb}
- \newcommand{\E}{\mathbb{E}}
- \DeclareMathOperator{\C}{Cov}
- \DeclareMathOperator{\V}{V}
- \DeclareMathOperator{\A}{AV}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Solution exercice 3.1


Le vrai paramètre à estimer est $t_{yU}=295.$
1. Dans l'exemple 3.1, on a calculé les probabilités de sélection  $p_k=x_k/\sum_{k\in U}x_k,~k=1, \ldots, 4,$ on les rappelle ci-dessous:
$$   
p_1=0.072, \quad p_2=0.359, \quad p_3=0.526, \quad p_4=0.043.
$$
Les supermarchés 3 et 4 ont été sélectionnés après $m=2$ tirages avec remise et proportionnels à $p_k, k\in U$ et on a donné dans l'exemple 3.1 l'estimation de Hansen-Hurwitz du total de $y.$ La variance de l'estimateur de Hansen-Hurwitz est donnée par 
$$
\V(\hat{t}_{y\rm{HH}})=\frac{1}{2}\sum_{k\in U}p_k\left(\frac{y_k}{p_k}-t_{yU}\right)^2=\frac{1}{2}\left(\sum_{k\in U}\frac{y^2_k}{p_k}-t^2_{yU}\right)\simeq 669.1884. 
$$
2. Pour obtenir une estimation de type Horvitz-Thompson, on calcule d'abord les probabilités d'inclusion $\pi_k$ par rapport à $p_k,~k\in U$ (voir chapitre 1):
\begin{eqnarray*}
  \pi_1=1-(1-p_1)^2\simeq 0.139 , \quad \pi_2=1-(1-p_2)^2\simeq 0.589, \\\pi_3=1-(1-p_3)^2\simeq 0.775, \quad \pi_4=1-(1-p_4)^2\simeq 0.084.  
\end{eqnarray*}
Les supermarchés 3 et 4 ont été sélectionnés, l'estimation de type Horvitz-Thompson du total de la variable $y$ est égale à 
$$
\hat{t}_{y\rm{HT}}=\frac{y_3}{\pi_3}+\frac{y_4}{\pi_4}=\frac{150}{0.775}+\frac{15}{0.084}\simeq 372.12. 
$$

Pour calculer la variance de l'estimateur de Horvitz-Thompson, on a besoin des probabilités d'inclusion d'ordre deux, $\pi_{kl}$ pour tous les $k\neq l\in U.$ On a (voir aussi le chapitre 1):
$$
\pi_{kl}=1-(1-p_k)^2-(1-p_l)^2+(1-p_k-p_l)^2, \quad k\neq l\in U
$$
et $\pi_{kl}=\pi_{lk}.$ On obtient 
\begin{eqnarray*}
\pi_{12}\simeq 0.052, \quad \pi_{13}\simeq 0.076, \quad \pi_{14}\simeq 0.006, \\\quad\pi_{23}\simeq 0.378, \quad\pi_{24}\simeq 0.031, \quad \pi_{34}\simeq 0.045. 
\end{eqnarray*}
La variance de l'estimateur de Horvitz-Thompson est alors égale à:
$$
\V(\hat{t}_{y\rm{HT}})=\sum_{k\in U}\sum_{l\in U}(\pi_{kl}-\pi_k\pi_l)\frac{y_k}{\pi_k}\frac{y_l}{\pi_l}\simeq 8594.28.
$$
3. Les deux estimateurs, de Hansen-Hurwitz et de Horvitz-Thompson, peuvent être utilisés pour estimer le total de $y:$ ils sont tous les deux sans biais et ils utilisent des poids inégaux. Néanmoins, l'estimateur de  Hansen-Hurwitz et surtout sa variance sont beaucoup plus simples à obtenir.   

## Solution exercice 3.2

1. L'estimateur de Horvitz-Thompson du total $y_{yU}$ est 
$$
\hat{t}_{y\rm{HT}}=\sum_{k\in s}\frac{y_k}{\pi_k},
$$
de variance donnée par 
$$
\V(\hat{t}_{y\rm{HT}})=\sum_{k\in U}(\pi_{kl}-\pi_k\pi_l)\frac{y_k}{\pi_k}\frac{y_l}{\pi_l}. 
$$
2. L'estimateur de Hansen-Hurwitz du total $y_{yU}$ pour $n$ tirages avec remise et avec des probabilités de sélection $p_k,~k\in U$ telles que $\pi_k=np_k, k\in U$ est égal à
$$
\hat{t}_{y\rm{HH}}=\frac{1}{n}\sum_{l=1}^n\frac{y_{k_l}}{p_{k_l}}=\sum_{l=1}^n\frac{y_{k_l}}{\pi_{k_l}}.
$$
On remarque que l'estimateur de Hansen-Hurvitz a la même expression que l'estimateur de Horvitz-Thompson, sa variance en revanche est différente et donnée par
$$
\V(\hat{t}_{y\rm{HH}})=\frac{1}{n}\sum_{k\in U}p_k\left(\frac{y_k}{p_k}-t_{yU}\right)^2=\frac{1}{n}\left(\sum_{k\in U}\frac{y_k^2}{p_k}-t^2_{yU}\right). 
$$
3. On écrit l'estimateur de la variance simplifié comme suit:
\begin{eqnarray*}
  \hat{V}_0(\hat{t}_{y\rm{HT}})&=&\frac{1}{n(n-1)}\sum_{k\in s}\left(\frac{y_k}{p_k}-\hat{t}_{y\rm{HT}}\right)^2\\
  &=& \frac{1}{n(n-1)}\sum_{k\in s}\frac{y^2_k}{p^2_k}-\frac{2\hat{t}_{y\rm{HT}}}{n(n-1)}\sum_{k\in s}\frac{y_k}{p_k}+\frac{1}{n(n-1)}n\hat{t}^2_{y\rm{HT}}\\
  &=& \frac{1}{n(n-1)}\sum_{k\in s}\frac{y^2_k}{p^2_k}-\frac{\hat{t}^2_{y\rm{HT}}}{n-1}=\frac{1}{n(n-1)}\sum_{k\in U}\frac{y^2_kI_k}{p^2_k}-\frac{\hat{t}^2_{y\rm{HT}}}{n-1},
\end{eqnarray*}
en utilisant le fait que $\pi_k=np_k,~k\in U.$ Pour calculer son biais, on utilise $\E(I_k)=\pi_k=np_k$ pour tout $k\in U$ et $\E(\hat{t}^2_{y\rm{HT}})=\V(\hat{t}_{y\rm{HT}})+t^2_{yU}.$ On obtient:
\begin{eqnarray*}
B(\hat{\V}_0(\hat{t}_{y\rm{HT}}))&=&\E(\hat{V}_0(\hat{t}_{y\rm{HT}}))-\V(\hat{t}_{y\rm{HT}})\\
&=& \frac{1}{n(n-1)}\sum_{k\in U}\frac{y^2_k\E(I_k)}{p^2_k}-\frac{\E(\hat{t}^2_{y\rm{HT}})}{n-1}-\V(\hat{t}_{y\rm{HT}})\\
&=& \frac{1}{n-1}\left(\sum_{k\in U}\frac{y_k^2}{p_k}-t^2_{yU}-\V(\hat{t}_{y\rm{HT}})\right)-\V(\hat{t}_{y\rm{HT}})\\
&=& \frac{1}{n-1}\left(n\V(\hat{t}_{y\rm{HH}})-\V(\hat{t}_{y\rm{HT}})\right)-\V(\hat{t}_{y\rm{HT}})\\
&=&\frac{n}{n-1}\left(\V(\hat{t}_{y\rm{HH}})-\V(\hat{t}_{y\rm{HT}})\right).
\end{eqnarray*}

## Solution exercice 3.3

Tout d'abord, le plan de sondage est sans remise et de taille fixe $n,$ les probabilités d'inclusion d'ordre un $\pi_k$ satisfont
$$
\sum_{k\in U}\pi_k=n.
$$
L'estimateur de Rao est donné par 
$$
\hat{t}_{y\rm{Rao}}=\frac{N}{n}\sum_{k\in s} y_k= \frac{N}{n}\sum_{k\in U} y_kI_k,
$$
où $I_k$ est la variable (aléatoire) indicatrice d'appartenance à un échantillon avec $\E(I_k)=\pi_k,$ pour $k\in U.$ Le biais de l'estimateur de Rao se calcule alors comme suit:
\begin{eqnarray*}
  B(\hat{t}_{y\rm{Rao}})&=& \E(\hat{t}_{y\rm{Rao}})-t_{yU}\\
  &=&\frac{N}{n}\sum_{k\in U} y_k\E(I_k)-t_{yU}=\frac{N}{n}\sum_{k\in U} y_k\pi_k-t_{yU}\\
  &=& \frac{N}{n}\sum_{k\in U} (y_k-\bar{y}_U+\bar{y}_U)\left(\pi_k-\frac{n}{N}+\frac{n}{N}\right)-t_{yU}\\
  &=& \frac{N}{n}\sum_{k\in U} (y_k-\bar{y}_U)\left(\pi_k-\frac{n}{N}\right)+\underbrace{\frac{N}{n}\sum_{k\in U} (y_k-\bar{y}_U)\frac{n}{N}}_{=0}+\underbrace{\frac{N}{n}\sum_{k\in U}\bar{y}_U\left(\pi_k-\frac{n}{N}\right)}_{=0}\\
  & & +\underbrace{\frac{N}{n}\sum_{k\in U}\bar{y}_U\frac{n}{N}}_{=t_{yU}}-t_{yU}\\
  &=& \frac{N}{n}\sum_{k\in U} (y_k-\bar{y}_U)\left(\pi_k-\frac{n}{N}\right)= \frac{N^2}{n}\mbox{Cov}(\mathbf{y}, \boldsymbol{\pi}),
\end{eqnarray*}
où $\mathbf{y}= (y_k)_{k\in U},$ $\boldsymbol{\pi}=(\pi_k)_{k\in U}$ et $\sum_{k\in U}\pi_k/N=n/N.$

## Solution exercice 3.4

Le plan de sondage de Poisson est un plan de sondage pour lequel la sélection des individus se fait de façon indépendante, donc les variables indicatrices d'appartenance à un échantillon $I_k,~k\in U$ sont indépendantes et $\pi_{kl}=\pi_k\pi_l$ pour $k\neq l\in U$.  Cela implique que les termes de covariance sont tous nuls, c'est-à-dire $\C(I_k, I_l)=\pi_{kl}-\pi_k\pi_l=0$ pour $k\neq l\in U.$ La variance de l'estimateur de Horvitz-Thompson $\hat t_{y\rm{HT}}$ du total $t_{yU}$ est égale à:
\begin{eqnarray*}
    \V_{\rm{PO}}(\hat t_{y\rm{HT}})=\sum_{k\in U}\pi_k(1-\pi_k)\frac{y_k^2}{\pi_k^2}+\sum_{k\in U}\sum_{l\in U, l\neq k}(\pi_{kl}-\pi_k\pi_l)\frac{y_k}{\pi_k}\frac{y_l}{\pi_l}=\sum_{k\in U}\frac{1-\pi_k}{\pi_k}y_k^2.
\end{eqnarray*}
La variance de l'estimateur de Horvitz-Thompson se simplifie dans le cas du plan de sondage de Poisson, elle est une somme sur $U$ des quantités $(1-\pi_k)y_k^2/\pi_k,~k\in U$ et en utilisant le principe de l'estimateur de Horvitz-Thompson, elle sera estimée sans biais par 
\begin{eqnarray*}
    \hat{\V}_{\rm{PO}}(\hat t_{y\rm{HT}})=\sum_{k\in s}\frac{1-\pi_k}{\pi^2_k}y_k^2.
\end{eqnarray*}    
Le même estimateur de la variance est obtenu en utilisant la formule générale de l'estimateur de la variance et le fait que les termes de covariance sont tous nuls. 

## Solution exercice 3.5

Pour un plan SI(n), on a $\pi_k=n/N=f$ pour tous les $k\in U.$  On calcule d'abord les quantités $a_k,~k\in U:$
$$
a_k=\frac{1-\pi_k}{\sum_{l\in s}(1-\pi_l)}=\frac{1-f}{n(1-f)}=\frac{1}{n}, \quad k\in U
$$
et l'estimateur de la variance devient
\begin{eqnarray*}
    \hat{V}_{Dev} (\hat{t}_{y\rm{HT}}) &=&\frac{1}{1-\frac{n}{n^2}}\sum_{k\in s}(1-f)\left(\frac{y_k}{f}-\frac{\frac{1-f}{f}\sum_{l\in s}y_l}{n(1-f)}\right)^2\\
    &=& \frac{n}{n-1}\frac{1-f}{f^2}\sum_{k\in s}(y_k-\bar{y}_s)^2=N^2\frac{1-f}{n}S^2_{ys},
\end{eqnarray*}
qui est l'estimateur de la variance de l'estimateur de Horvitz-Thompson dans le cas d'un plan SI. 

## Solution exercice 3.6

L'approximation de H\'ajek consiste à approcher les termes de covariance $\Delta_{kl}=\pi_{kl}-\pi_k\pi_l, k\neq l$ par une quantité qui dépend uniquement des probabilités d'inclusion d'ordre un:
$$
\pi_{kl}-\pi_k\pi_l \simeq -\pi_k\pi_l\frac{(1-\pi_k)(1-\pi_l)}{d(\pi)}, \quad k\neq l\in U,
$$
où $d(\pi)=\sum_{k\in U}\pi_k(1-\pi_k)$. La variance de type Yates-Grundy-Sen devient:
\begin{eqnarray*}
\V(\hat{t}_{y\rm{HT}})&=&-\frac{1}{2}\sum_{k\in U}\sum_{l\in U}(\pi_{kl}-\pi_k\pi_l)\left(\frac{y_k}{\pi_k}-\frac{y_l}{\pi_l}\right)^2\\
&\simeq& \frac{1}{2d(\pi)}\sum_{k\in U}\sum_{l\neq k\in U}\pi_k\pi_l(1-\pi_k)(1-\pi_l)\left(\frac{y_k}{\pi_k}-\frac{y_l}{\pi_l}\right)^2\\
&=& \frac{1}{2d(\pi)}\sum_{k\in U}\sum_{l\in U}\pi_k\pi_l(1-\pi_k)(1-\pi_l)\left(\frac{y^2_k}{\pi_k^2}-2\frac{y_k}{\pi_k}\frac{y_l}{\pi_l}+\frac{y^2_l}{\pi_l^2}\right)\\
&=& \frac{1}{d(\pi)}\left(\sum_{k\in U}\pi_k(1-\pi_k)\frac{y^2_k}{\pi_k^2}\right)\underbrace{\sum_{l\in U}\pi_l(1-\pi_l)}_{d(\pi)}-\frac{1}{d(\pi)}\left(\sum_{k\in U}y_k(1-\pi_k)\right)^2\\
&=& \left(\sum_{k\in U}\pi_k(1-\pi_k)\frac{y^2_k}{\pi_k^2}\right)-\frac{1}{d(\pi)}\left(\sum_{k\in U}y_k(1-\pi_k)\right)^2\\
&=& \sum_{k\in U}\pi_k(1-\pi_k)\left(\frac{y_k}{\pi_k}-A\right)^2,
\end{eqnarray*}
où $A=\sum_{l\in U}y_l(1-\pi_l)/d(\pi).$


## Solution exercice 3.7

1. On montre que le plan de sondage de Bernoulli de paramètre $\pi=1/2$ est le plan à entropie maximale parmi tous les plans de sondage $p(\cdot),$  définis  $U.$ Plus précisément,  $p(s)$ est la probabilité de sélection un échantillon $s,$  $s\in \mathcal S$ et $\mathcal S$ est m'ensemble des parties de $U.$ 



L'entropie de Shannon d'un plan $p$ sur $\mathcal{S}$ est définie par
$$
H(p)
=
-\sum_{s\in\mathcal{S}}
p(s)\log p(s).
$$
On cherche à maximiser $H(p)$ sous la contrainte:
\begin{equation}  
\sum_{s\in\mathcal{S}} p(s) = 1.   
\end{equation}
La fonction lagrangien s'écrit
$$
\mathcal{L}(p; \alpha)
=
-\sum_{s\in \mathcal{S}} p(s)\log p(s)
+
\alpha\Big(\sum_{s\in\mathcal{S}} p(s)-1\Big),
$$
où $\alpha\in \mathbf{R}$ est le multiplicateur de Lagrange. 
Pour tout $s\in \mathcal{S}$, on dérive par rapport à
$p(s)$ et on égalise à 0:
$$
\frac{\partial\mathcal{L}}{\partial p(s)}
=
-(\log p(s)+1)
+
\alpha=0.
$$
On obtient donc 
$p(s)=\exp{(\alpha-1)},$ pour tout $s\in \mathcal{S}.$
A partir de la contrainte, on déduit:
$$
\sum_{s\in\mathcal{S}} p(s) = \sum_{s\in\mathcal{S}} \exp{(\alpha-1)}=2^N \exp{(\alpha-1)}=1,$$
d'où $\exp{(\alpha-1)}=1/2^N$ et  $p(s)=1/2^N.$
D'autre part, le plan de sondage de Bernoulli de paramètre $\pi=1/2$ s'écrit:
$$
p_{\rm{BE}}(s)=\prod_{k\in s}\pi\prod_{k\notin s} (1-\pi)=\prod_{k\in U} 1/2=1/2^N,
$$ 
pour tout $s\in \mathcal{S},$ d'où le résultat. 

2. 
On montre que le plan simple sans remise est le plan à entropie maximale dans la classe des plans de taille fixe, à probabilités égales et sans remise.

On suppose que la taille de l'échantillon est $n$ et donc les probabilités d'inclusion sont $\pi_k=n/N, k\in U.$ Soit $\mathcal{S}_n$ l'ensemble de tous les échantillons $s\subseteq U$ de taille fixe $n.$ Le cardinal de $\mathcal{S}_n$ est $\begin{pmatrix} 
N\\
n\\
\end{pmatrix},$ le nombre de parties à $n$ éléments parmi $N.$ On cherche à maximiser 
$$
H_n(p)
=
-\sum_{s\in\mathcal{S}_n}
p(s)\log p(s)
$$
sous la contrainte:
\begin{equation}
\sum_{s\in\mathcal{S}_n} p(s) = 1. 
\end{equation}
En procédant comme au point précédent, on obtient:
$p(s)=\exp{(\alpha-1)},$ pour tout $s\in \mathcal{S}_n$ et 

$$
\sum_{s\in\mathcal{S}_n} p(s) = \sum_{s\in\mathcal{S}_n} \exp{(\alpha-1)}=\begin{pmatrix} 
N\\
n\\
\end{pmatrix}
\exp{(\alpha-1)}=1,$$
d'où $\exp{(\alpha-1)}=1/\begin{pmatrix} 
N\\
n\\
\end{pmatrix}$ et  $p(s)=1/\begin{pmatrix} 
N\\
n\\
\end{pmatrix}.$ D'autre part, le plan simple sans remise SI de taille $n$ s'écrit:
$$
p_{\rm{SI}}(s)=1/\begin{pmatrix} 
N\\
n\\
\end{pmatrix},
$$
pour tout $s\in \mathcal{S}_n,$ d'où le résultat. 

3. On montre que le plan de Poisson est le plan à entropie maximale dans la classe des plans sans remise à probabilités d'inclusion inégales $\pi_k, k\in U,$ et fixées a priori. On cherche à maximiser $H(p)$ sous les contraintes suivantes:
\begin{eqnarray}
\sum_{s\in\mathcal{S}} p(s) &=& 1, \label{eqnormalisation}\\
\sum_{s\in\mathcal{S}, k\in s} p(s)& =&\sum_{s\in\mathcal{S}} I_k p(s) = \pi_k,
\qquad k\in U, \label{eqinclusion}
\end{eqnarray}
où $I_k$ est la variable indicatrice associée à l'unité $k\in U.$ La fonction lagrangien est donnée par
\begin{eqnarray*}
\mathcal{L}(p;\alpha, \beta_1, \ldots, \beta_N)=-\sum_{s\in \mathcal S}p(s)\log p(s)+\alpha(\sum_{s\in \mathcal S}p(s)-1)+\sum_{k\in U}\beta_k\left(\sum_{s\in\mathcal{S}} I_kp(s)-\pi_k\right)
\end{eqnarray*}
où $\alpha$ et $b_1,\dots,b_N$ sont les multiplicateurs de Lagrange associés
aux $N+1$ contraintes. Pour tout $s\in \mathcal{S}$, on dérive $\mathcal{L}$ par rapport à
$p(s)$ :

$$
\frac{\partial\mathcal{L}}{\partial p(s)}
=
-(\log p(s)+1)
+
\alpha
+
\sum_{k=1}^N \beta_k I_k
=0.
$$
On obtient donc
$$
\log p(s)
=
\alpha-1+\sum_{k=1}^N \beta_k I_k,
$$
et
$$
p(s)
=
C\exp\!\Big(\sum_{k=1}^N \beta_k I_k\Big),
\qquad
C=e^{\alpha-1}.
$$
La constante $C$ est déterminée en utilisant la contrainte:
$$
1
=
\sum_{s\in\mathcal{S}} p(s)
=
C
\sum_{s\in\mathcal{S}}
\exp\!\Big(\sum_{k=1}^N \beta_k I_k\Big).
$$
Or on peut montrer (par exemple, par induction) que 
$$
\sum_{s\in\mathcal{S}}
\exp\!\Big(\sum_{k=1}^N \beta_k I_k\Big)
=
\prod_{k=1}^N (1+e^{\beta_k}),
$$
ce qui nous permet de déduire l'expression de la constante $C:$
$$
C=\prod_{k=1}^N \frac{1}{1+e^{\beta_k}}. 
$$
L'expression du plan de sondage $p(\cdot)$ vérifiant le problème d'optimisation peut-être ensuite obtenue:
$$
p(s)
=
\prod_{k=1}^N
\frac{e^{\beta_k I_k}}{1+e^{\beta_k}}.
$$
D'autre part, par définition,
$$
\pi_k=P(I_k=1)=
\sum_{s\in\mathcal{S}, I_k=1} p(s).
$$
En utilisant l'expression précédente de $p(s)$, on obtient
$$
\pi_k
=
\frac{e^{\beta_k}}{1+e^{\beta_k}}
\sum_{I_j=0, \atop j\in U, j\neq k}^1
\prod_{l\in U \atop l\neq k}
\frac{e^{\beta_l I_l}}{1+e^{\beta_l}}=\frac{e^{\beta_k}}{1+e^{\beta_k}}
$$
car
$$
\sum_{I_j=0,\atop j\in U, j\neq k}^1
\prod_{l\in U \atop l\neq k}
\frac{e^{\beta_j I_l}}{1+e^{\beta_l}}
=
\prod_{l\in U \atop l\neq k}
\left(
\sum_{I_j=0}^1
\frac{e^{\beta_j I_j}}{1+e^{\beta_j}}
\right)
=1.
$$


On peut donc écrire
$$
p(s)
=
\prod_{k=1}^N
\pi_k^{\,I_k}
(1-\pi_k)^{1-I_k}=\prod_{k\in s} 
\pi_k
\prod_{k\notin s}(1-\pi_k).
$$
Ceci correspond au plan de Poisson avec les probabilités $\pi_k, k\in U.$

4. On montre que le plan de Poisson conditionnel est le plan à entropie maximale dans la classe des plans sans remise, de taille fixe, à probabilités inégales et fixées a priori.


On suppose que les probabilités d'inclusion $\pi_k$ sont fixées et $\sum_{k\in U} \pi_k=n.$ On cherche à maximiser $H_n(p)$ sous les contraintes :
\begin{align}
\sum_{s\in\mathcal{S}_n} p(s) &= 1, \label{eq:norm_n}\\
\sum_{s\in\mathcal{S}_n, k\in s} p(s) &= \pi_k,
\qquad k=1,\dots,N. \label{eq:incl_n}
\end{align}
On procède comme précédemment et on obtient
$$
\log p(s)
=
\alpha-1+\sum_{k=1}^N \beta_k I_k,
$$
ou, de façon équivalente:
$$
p(s)
=
C\exp\!\Big(\sum_{k=1}^N \beta_k I_k\Big),
\qquad
C=e^{\alpha-1}.
$$

Comme $p(s)=0$ pour $s\notin\mathcal{S}_n$,
la loi obtenue est une loi conditionnée à
$\sum_{k\in U} I_k=n$. On peut écrire, pour tout $s\in\mathcal{S}_n$,
$$
p(s)
=
\frac{\prod_{k=1}^N e^{\beta_k I_k}}
{\sum_{s'\in\mathcal{S}_n}
\prod_{k=1}^N e^{\beta_k I_k}}.$$

En utilisant
$$
w_k = e^{\beta_k} > 0\,, k\in U, 
$$
on obtient
$$
p(s)
=
\frac{\prod_{k=1}^N w_k^{\,I_k}}
{\sum_{s'\in\mathcal{S}_n}
\prod_{k=1}^N w_k^{\,I_k}}=
\frac{\prod_{k\in s} w_k}
{\sum_{s'\in\mathcal{S}_n} \prod_{k\in s'} w_k},
\qquad s\in\mathcal{S}_n.
$$

Pour tout $s\in \mathcal{S}_n$, on a donc 
\begin{equation}
p(s)
=
\frac{\prod_{k\in s} w_k}
{\sum_{s'\in \mathcal{S}_n} \prod_{k\in s'} w_k}.
\end{equation}

Soit $\tilde{p}(\cdot)$ le plan de Poisson avec les probabilités d'inclusion d'ordre un $P(k\in s)=w_k/(1+w_k), k\in U.$ La loi donnée par l'expression du plan de sondage obtenue ci-dessous est celle du
plan de Poisson conditionnel à la taille (ou le plan rejectif) :
$$
p(s)
=
\tilde{p}(s \mid s\in \mathcal{S}_n).
$$

L'entropie est une fonction strictement concave sur le simplexe des lois définies sur $\mathcal{S}_n$ et les contraintes sont linéaires.

Il résulte que le plan rejectif est l'unique maximum global. Donc, le plan de Poisson conditionnel à la taille est le plan de maximum d'entropie parmi tous les plans de sondage de taille fixe $n$ ayant les mêmes probabilités d'inclusion d'ordre un $\pi_k, k\in U.$




