---
title: "I. Présentation"
header-includes: \usepackage{amsmath,amssymb}
---

<!-- ÉCRIVEZ VOTRE CODE R MARKDOWN ICI -->
<!-- Cette page est la page d'accueil / Présentation du site -->
## Les auteures

 - [Camelia Goga](https://goga.perso.math.cnrs.fr) est professeure de mathématiques appliqués, spécialité statistique au sein du Laboratoire de Mathématiques de Besançon, Université Marie et Louis Pasteur. Ses thématiques de recherche sont la théorie des sondages, la statistique nonparamétrique, l'apprentissage statistique. 
 
 - **Hélène Juillard** possède un doctorat en mathématiques appliquées, statistique à l'Université Toulouse 1 Capitole réalisé en collaboration avec l'Ined. Elle enseigne actuellement les techniques de sondages dans le cadre de l'enseignement à distance. 
 
 - [Alina Matei](https://libra.unine.ch/entities/person/a44b172f-bff3-4312-89eb-be682028c603) est professeur titulaire de statistique à l'Université de Neuchâtel (Suisse). Elle mène des recherches sur divers sujets liés à l'échantillonnage et à l'estimation en populations finies.
 
 - [Anne M. Ruiz](https://www.tse-fr.eu/fr/people/anne-m-ruiz) est professeur de mathématiques appliqués, spécialité statistique au sein de Toulouse School of Economics. Ses thématiques de recherche privilégiées sont l'analyse de données multivariée, la théorie des sondages, l'économétrie et la statistique spatiales.


\vspace{1cm}


## Résumé du Tome 1

Dans ce premier tome de l'ouvrage *Techniques de sondage: de la théorie à la pratique avec R*, les principales méthodes de tirage d'échantillon et d'estimation de totaux et de moyennes sont présentées d'un point de vue théorique, puis mises en oeuvre avec R,  à partir d'exemples inspirés de situations réelles classiques.
Le cadre étudié est celui d'une population finie où l'inférence statistique repose sur le tirage aléatoire des unités et sur des méthodes d’estimation adaptées à ce cadre.  

\medskip 
Ce premier tome étudie les stratégies d'échantillonnage probabilistes élémentaires, à probabilités égales ou inégales, avec ou sans remise, utilisant les estimateurs classiques de Horvitz-Thompson et Hansen-Hurwitz. Les plans de sondage stratifiés, en grappes et à deux degrés y sont également décrits de manière détaillée. De nombreux exemples numériques et applications à des enquêtes réelles facilitent la compréhension des résultats théoriques. 
Des études par simulation Monte-Carlo complètent l'analyse  en évaluant les performances statistiques (biais et variance) des estimateurs sous différents plans de sondage, soulignant les avantages, les limites et les pistes d'amélioration possibles des stratégies étudiées.



\medskip

Alliant rigueur théorique et mise en oeuvre pratique avec R, l'ouvrage  s'adresse à toutes celles et ceux qui souhaitent maîtriser les principes et l'application des techniques de sondage. Les auteures, qui enseignent les sondages et la statistique depuis de nombreuses années et ont acquis une solide pratique professionnelle grâce aux nombreuses collaborations avec l'Ined, La Poste, Edf, mettent ici à profit leur expérience pédagogique et leur connaissance approfondie du domaine. Le *Tome 1* constitue une ressource précieuse pour un cours de sondages de niveau débutant ou intermédiaire,  tandis que le *Tome 2* est consacré aux méthodes avancées: échantillonnage spatial, estimation de paramètres non-linéaires, estimation avec prise en compte d'information auxiliaire, théorie asymptotique.

## Table de matières

## Résumé du Tome 2

